device: "cuda" 
## Model definition
model: Raw_ECAPA
test_threshold: 0.477571964263916

nOut: 512
n_mfcc: 80
n_mels: 80
features: melspectrogram
nClasses: 3153 # cb: 13897 cskh: 20000 mix 33897

criterion: AAmSoftmax 
optimizer: AdaBelief
step_size: 10
########################################################################
## Paths
save_path: backup 

# Model Path
initial_model_infer: backup/Raw_ECAPA/model/cb_0310_v4_eer3e-1.model

## Data Loader definition
nDataLoaderThread: 1 
batch_size: 16
sample_rate: 8000
max_frames: 200
eval_frames: 200
num_eval: 20

target_format: wav

augment: False
augment_chain: None

cohorts_path: backup/Raw_ECAPA/cohorts_callbot.npy
scoring_mode: cosine