device: "cuda" 
## Model definition
model: Raw_ECAPA
test_threshold: 0.3272123336791992
# Model Path
initial_model_infer: backup/Raw_ECAPA/model/cb_0324_ge2e_v1.model
# Model settings
nOut: 512
n_mfcc: 80
n_mels: 80
features: raw
nClasses: 3153 # cb: 13897 cskh: 20000 mix 33897

criterion: AAmSoftmax 
optimizer: AdaBelief
step_size: 10
########################################################################
## Paths
save_path: backup 
test_path: log_service/check_log_combine/
test_list: log_service/check_log_combine/equitable_test.txt # private test 
ref: log_service/check_log_combine/equitable_test_truth.txt
com: log_service/check_log_combine/test_result.txt

## Data Loader definition
nDataLoaderThread: 1 
batch_size: 16
sample_rate: 8000
max_frames: 100
eval_frames: 100
num_eval: 20

augment: False

cohorts_path: backup/Raw_ECAPA/cohorts_callbot.npy
scoring_mode: cosine

# initial_model_infer: backup/Raw_ECAPA/model/mix_0307_1357_v3.model # 0.5394577383995056 0.5229600071907043 0.5437501668930054
# initial_model_infer: backup/Raw_ECAPA/model/cb_0325_v1.model # 0.34933072328567505
# initial_model_infer: backup/Raw_ECAPA/model/cb_0324_ge2e_v1.model # 0.3272123336791992
# initial_model_infer: backup/Raw_ECAPA/model/cb_0329_v0.model # 0.25866398215293884
# initial_model_infer: backup/MsLoss/Raw_ECAPA/model/cb_0331_ms_am_364.model #  0.26218727231025696