device: "cuda"

## Model definition
model: Raw_ECAPA
nOut: 512
n_mels: 80
features: raw
criterion: GE2ELossV2 
nClasses: 14142 

## Loader definition
nDataLoaderThread: 1 
sample_rate: 8000
eval_frames: 100 
max_frames: 100
batch_size: 64
augment: False

## others
step_size: 5
scoring_mode: cosine

## path
test_list: dataset/test_callbot_raw/test_cb_v1.txt # full test
save_path: backup 
 # test_list: dataset/test_trial_file_converted_new.txt  # half test
cohorts_path: backup/Raw_ECAPA/cohorts_callbot.npy
initial_model_infer: backup/Raw_ECAPA/model/cb_0324_ge2e_v1.model
# Raw_ECAPA backup/Raw_ECAPA/model/mix_0307_1357_v3.model backup/Raw_ECAPA/model/mix_0321_v1_fullaug.model backup/Raw_ECAPA/model/cb_0329_v0.model backup/Raw_ECAPA/model/cb_0324_ge2e_v1.model backup/Raw_ECAPA/model/cb_0325_v1.model










