device: "cuda"
## Model definition
model: ECAPA_TDNN
nOut: 192
n_mfcc: 80
n_mels: 80
features: melspectrogram
lib: nnAudio
nClasses: 5207 # cb: 13897 cskh: 20000 mix 33897

criterion: AAmSoftmax 
margin: 0.2
scale: 30

optimizer: AdaBelief
weight_decay: 0.00002
lr_decay: 0.95

callbacks: cosine_annealinglr
step_size: 10
es_patience: 15

## Data loade definition
max_epoch: 500 
batch_size: 32
nDataLoaderThread: 0
max_seg_per_spk: 1000
nPerSpeaker: 2

max_frames: 300
eval_frames: 300
sample_rate: 8000
augment_chain: env_corrupt time_domain spec_domain
test_interval: -1

## Paths
train_list: dataset/mixed_data_train_v5.txt
test_list: dataset/train_callbot_v2/val_def_20.txt 
save_path: backup/

initial_model: backup/ECAPA_TDNN/AAmSoftmax/model/best_state.pt
initial_model_infer: backup/Raw_ECAPA/model/best_state.model


