device: "cuda"

## Model definition
model: Raw_ECAPA
nOut: 512
n_mels: 80
features: raw
criterion: AAmSoftmax 
nClasses: 14142 

augment: False
augment_chain: []
scheduler_step: 10
optimizer: AdaBelief
callbacks: cosine_annealinglr
max_epoch: 500

## Loader definition
nDataLoaderThread: 1 
sample_rate: 8000
eval_frames: 300 
max_frames: 300
batch_size: 64
augment: False

## others
step_size: 5
scoring_mode: cosine

## path
train_list: dataset/mixed_data_train_v5.txt
test_list: dataset/test_callbot_raw/test_cb_v1.txt # full test
save_path: backup 

cohorts_path: backup/Raw_ECAPA/AAmSoftmax/cohorts.npy
initial_model_infer: backup/Raw_ECAPA/AAmSoftmax/model/best_state.pt

# Raw_ECAPA backup/Raw_ECAPA/model/mix_0307_1357_v3.model backup/Raw_ECAPA/model/mix_0321_v1_fullaug.model backup/Raw_ECAPA/model/cb_0329_v0.model backup/Raw_ECAPA/model/cb_0324_ge2e_v1.model backup/Raw_ECAPA/model/cb_0325_v1.model










